USE FINALLAB;

DROP TABLE IF EXISTS CLIENTS;
CREATE TABLE CLIENTS (
--  ID int NOT NULL AUTO_INCREMENT,
  EMAIL varchar(60)  UNIQUE default 0,
  PASSWORD varchar(12)  default 0,
  BOOK varchar(60)  DEFAULT '',
  PRIMARY KEY (EMAIL)
) ENGINE=InnoDB;