DROP DATABASE IF EXISTS FINALLAB;
CREATE DATABASE FINALLAB;

USE FINALLAB;

DROP USER IF EXISTS fish@localhost;
CREATE USER fish@'localhost' IDENTIFIED WITH mysql_native_password BY 'kfstandard' REQUIRE NONE;
GRANT ALL ON FINALLAB.* TO fish@'localhost';

FLUSH PRIVILEGES;
